/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedConnectionsIndexRouteImport } from './routes/_authed/connections/index'
import { Route as AuthedAppsIndexRouteImport } from './routes/_authed/apps/index'
import { Route as AuthedOrgSettingsRouteImport } from './routes/_authed/org/settings'
import { Route as AuthedOrgCreateRouteImport } from './routes/_authed/org/create'
import { Route as AuthedConnectionsNewRouteImport } from './routes/_authed/connections/new'
import { Route as AuthedConnectionsConnectionIdRouteImport } from './routes/_authed/connections/$connectionId'
import { Route as AuthedAppsAppIdRouteImport } from './routes/_authed/apps/$appId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConnectionsIndexRoute = AuthedConnectionsIndexRouteImport.update({
  id: '/connections/',
  path: '/connections/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppsIndexRoute = AuthedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgSettingsRoute = AuthedOrgSettingsRouteImport.update({
  id: '/org/settings',
  path: '/org/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgCreateRoute = AuthedOrgCreateRouteImport.update({
  id: '/org/create',
  path: '/org/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConnectionsNewRoute = AuthedConnectionsNewRouteImport.update({
  id: '/connections/new',
  path: '/connections/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConnectionsConnectionIdRoute =
  AuthedConnectionsConnectionIdRouteImport.update({
    id: '/connections/$connectionId',
    path: '/connections/$connectionId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAppsAppIdRoute = AuthedAppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/apps/$appId': typeof AuthedAppsAppIdRoute
  '/connections/$connectionId': typeof AuthedConnectionsConnectionIdRoute
  '/connections/new': typeof AuthedConnectionsNewRoute
  '/org/create': typeof AuthedOrgCreateRoute
  '/org/settings': typeof AuthedOrgSettingsRoute
  '/apps/': typeof AuthedAppsIndexRoute
  '/connections/': typeof AuthedConnectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/apps/$appId': typeof AuthedAppsAppIdRoute
  '/connections/$connectionId': typeof AuthedConnectionsConnectionIdRoute
  '/connections/new': typeof AuthedConnectionsNewRoute
  '/org/create': typeof AuthedOrgCreateRoute
  '/org/settings': typeof AuthedOrgSettingsRoute
  '/apps': typeof AuthedAppsIndexRoute
  '/connections': typeof AuthedConnectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/apps/$appId': typeof AuthedAppsAppIdRoute
  '/_authed/connections/$connectionId': typeof AuthedConnectionsConnectionIdRoute
  '/_authed/connections/new': typeof AuthedConnectionsNewRoute
  '/_authed/org/create': typeof AuthedOrgCreateRoute
  '/_authed/org/settings': typeof AuthedOrgSettingsRoute
  '/_authed/apps/': typeof AuthedAppsIndexRoute
  '/_authed/connections/': typeof AuthedConnectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/apps/$appId'
    | '/connections/$connectionId'
    | '/connections/new'
    | '/org/create'
    | '/org/settings'
    | '/apps/'
    | '/connections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/apps/$appId'
    | '/connections/$connectionId'
    | '/connections/new'
    | '/org/create'
    | '/org/settings'
    | '/apps'
    | '/connections'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/apps/$appId'
    | '/_authed/connections/$connectionId'
    | '/_authed/connections/new'
    | '/_authed/org/create'
    | '/_authed/org/settings'
    | '/_authed/apps/'
    | '/_authed/connections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/connections/': {
      id: '/_authed/connections/'
      path: '/connections'
      fullPath: '/connections/'
      preLoaderRoute: typeof AuthedConnectionsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/apps/': {
      id: '/_authed/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthedAppsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/org/settings': {
      id: '/_authed/org/settings'
      path: '/org/settings'
      fullPath: '/org/settings'
      preLoaderRoute: typeof AuthedOrgSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/org/create': {
      id: '/_authed/org/create'
      path: '/org/create'
      fullPath: '/org/create'
      preLoaderRoute: typeof AuthedOrgCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/connections/new': {
      id: '/_authed/connections/new'
      path: '/connections/new'
      fullPath: '/connections/new'
      preLoaderRoute: typeof AuthedConnectionsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/connections/$connectionId': {
      id: '/_authed/connections/$connectionId'
      path: '/connections/$connectionId'
      fullPath: '/connections/$connectionId'
      preLoaderRoute: typeof AuthedConnectionsConnectionIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/apps/$appId': {
      id: '/_authed/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AuthedAppsAppIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedAppsAppIdRoute: typeof AuthedAppsAppIdRoute
  AuthedConnectionsConnectionIdRoute: typeof AuthedConnectionsConnectionIdRoute
  AuthedConnectionsNewRoute: typeof AuthedConnectionsNewRoute
  AuthedOrgCreateRoute: typeof AuthedOrgCreateRoute
  AuthedOrgSettingsRoute: typeof AuthedOrgSettingsRoute
  AuthedAppsIndexRoute: typeof AuthedAppsIndexRoute
  AuthedConnectionsIndexRoute: typeof AuthedConnectionsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedAppsAppIdRoute: AuthedAppsAppIdRoute,
  AuthedConnectionsConnectionIdRoute: AuthedConnectionsConnectionIdRoute,
  AuthedConnectionsNewRoute: AuthedConnectionsNewRoute,
  AuthedOrgCreateRoute: AuthedOrgCreateRoute,
  AuthedOrgSettingsRoute: AuthedOrgSettingsRoute,
  AuthedAppsIndexRoute: AuthedAppsIndexRoute,
  AuthedConnectionsIndexRoute: AuthedConnectionsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
