/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SignUpRouteImport } from "./routes/sign-up";
import { Route as SignInRouteImport } from "./routes/sign-in";
import { Route as ConnectionsRouteImport } from "./routes/connections";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as OrgCreateRouteImport } from "./routes/org/create";
import { Route as ConnectIncomingRouteImport } from "./routes/connect/incoming";
import { Route as AuthCallbackRouteImport } from "./routes/auth/callback";
import { Route as ApiSplatRouteImport } from "./routes/api.$";
import { Route as ApiRpcSplatRouteImport } from "./routes/api.rpc.$";

const SignUpRoute = SignUpRouteImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => rootRouteImport,
} as any);
const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any);
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: "/connections",
  path: "/connections",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const OrgCreateRoute = OrgCreateRouteImport.update({
  id: "/org/create",
  path: "/org/create",
  getParentRoute: () => rootRouteImport,
} as any);
const ConnectIncomingRoute = ConnectIncomingRouteImport.update({
  id: "/connect/incoming",
  path: "/connect/incoming",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: "/auth/callback",
  path: "/auth/callback",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: "/api/$",
  path: "/api/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: "/api/rpc/$",
  path: "/api/rpc/$",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/connections": typeof ConnectionsRoute;
  "/sign-in": typeof SignInRoute;
  "/sign-up": typeof SignUpRoute;
  "/api/$": typeof ApiSplatRoute;
  "/auth/callback": typeof AuthCallbackRoute;
  "/connect/incoming": typeof ConnectIncomingRoute;
  "/org/create": typeof OrgCreateRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/connections": typeof ConnectionsRoute;
  "/sign-in": typeof SignInRoute;
  "/sign-up": typeof SignUpRoute;
  "/api/$": typeof ApiSplatRoute;
  "/auth/callback": typeof AuthCallbackRoute;
  "/connect/incoming": typeof ConnectIncomingRoute;
  "/org/create": typeof OrgCreateRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/connections": typeof ConnectionsRoute;
  "/sign-in": typeof SignInRoute;
  "/sign-up": typeof SignUpRoute;
  "/api/$": typeof ApiSplatRoute;
  "/auth/callback": typeof AuthCallbackRoute;
  "/connect/incoming": typeof ConnectIncomingRoute;
  "/org/create": typeof OrgCreateRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/connections"
    | "/sign-in"
    | "/sign-up"
    | "/api/$"
    | "/auth/callback"
    | "/connect/incoming"
    | "/org/create"
    | "/api/rpc/$";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/about"
    | "/connections"
    | "/sign-in"
    | "/sign-up"
    | "/api/$"
    | "/auth/callback"
    | "/connect/incoming"
    | "/org/create"
    | "/api/rpc/$";
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/connections"
    | "/sign-in"
    | "/sign-up"
    | "/api/$"
    | "/auth/callback"
    | "/connect/incoming"
    | "/org/create"
    | "/api/rpc/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  ConnectionsRoute: typeof ConnectionsRoute;
  SignInRoute: typeof SignInRoute;
  SignUpRoute: typeof SignUpRoute;
  ApiSplatRoute: typeof ApiSplatRoute;
  AuthCallbackRoute: typeof AuthCallbackRoute;
  ConnectIncomingRoute: typeof ConnectIncomingRoute;
  OrgCreateRoute: typeof OrgCreateRoute;
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/sign-up": {
      id: "/sign-up";
      path: "/sign-up";
      fullPath: "/sign-up";
      preLoaderRoute: typeof SignUpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sign-in": {
      id: "/sign-in";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof SignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/connections": {
      id: "/connections";
      path: "/connections";
      fullPath: "/connections";
      preLoaderRoute: typeof ConnectionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/org/create": {
      id: "/org/create";
      path: "/org/create";
      fullPath: "/org/create";
      preLoaderRoute: typeof OrgCreateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/connect/incoming": {
      id: "/connect/incoming";
      path: "/connect/incoming";
      fullPath: "/connect/incoming";
      preLoaderRoute: typeof ConnectIncomingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/callback": {
      id: "/auth/callback";
      path: "/auth/callback";
      fullPath: "/auth/callback";
      preLoaderRoute: typeof AuthCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/$": {
      id: "/api/$";
      path: "/api/$";
      fullPath: "/api/$";
      preLoaderRoute: typeof ApiSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/rpc/$": {
      id: "/api/rpc/$";
      path: "/api/rpc/$";
      fullPath: "/api/rpc/$";
      preLoaderRoute: typeof ApiRpcSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConnectionsRoute: ConnectionsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ConnectIncomingRoute: ConnectIncomingRoute,
  OrgCreateRoute: OrgCreateRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
